### ISSUE TITLE
Request for sharing datasets and checkpoints in BaiduYun

### ISSUE THREAD

**Issue by zhixuanli** [apchenstu/SLN-Amodal#3]
Request for sharing datasets and checkpoints in BaiduYun.

It's hard for many people from mainland China to download from Google Drive.

Could you please provide the download link of BaiduYun?

Thank you so much!

**Comment by Jack12xl** [comment]
Link uploaded as 链接:https://pan.baidu.com/s/1zyJAXZmNw5lFdr3DBuaYiQ  密码:yr2i

**Comment by zhixuanli** [comment]
Thanks!!
